trigger: none
pr: none

schedules:
- cron: "0 12 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - develop
  always: true


variables:
  package_name: boost_histogram

jobs:


- job: LinuxCMake
  strategy:
    matrix:
      Python37:
        python.version: '3.8'
        python.architecture: 'x64'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - template: azure-wheel-helpers/azure-setup.yml
    - template: azure-live-at-head.yml
    - template: azure-wheel-helpers/azure-cmake-steps.yml

